apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-api
spec:
  selector:
    matchLabels:
      app: server-api
  template:
    metadata:
      labels:
        app: server-api
    spec:
      terminationGracePeriodSeconds: 5
      initContainers:
      - name: init-db
        image: busybox
        command: ['sh', '-c', 'until nslookup database; do echo waiting for mysql service; sleep 2; done;']
      containers:
      - name: server
        image: ajaypspk/server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_HOST
          value: "database"
---
apiVersion: v1
kind: Service
metadata:
  name: server-api
spec:
  type: LoadBalancer
  clusterIP: 10.96.5.11
  selector:
    app: server-api
  ports:
  - name: service
    port: 8080
    nodePort: 30100
    targetPort: 8080
status:
  loadBalancer:
    ingress:
    - ip: 10.96.5.10
